name: quickcare_driver
description: "SmartAmbulance Driver App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.5.0
  firebase_storage: ^11.5.6
  file_picker: ^8.0.3
  device_info_plus: ^9.1.0
  path_provider: ^2.1.1
  open_file: ^3.3.2
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true